[package]
name = "system_config"
version.workspace = true
edition = "2021"
authors = ["BuckyOS DAO","@waterflier"]

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html


[dependencies]
time = { workspace = true }
async-trait = { workspace = true }
log = { workspace = true }
simplelog = { workspace = true }
serde = { workspace = true }
serde_json = { workspace = true }
url = { workspace = true }
tokio = { workspace = true }
sled = { workspace = true }
lazy_static = { workspace = true }
thiserror = { workspace = true }
jsonwebtoken = { workspace = true }
# rocksdb = "*"
buckyos-kit = { workspace = true }
name-lib = { workspace = true }
kRPC = { workspace = true }
rbac = { workspace = true }


