[package]
name = "system_config"
version.workspace = true
edition = "2021"
authors = ["BuckyOS DAO","@waterflier"]

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html


[dependencies]
time = { version = "^0.3", features = ["formatting"] }
async-trait = "*"
log = "*"
simplelog = "*"
serde = "*"
serde_json = "*"
url = "*"
tokio = { version = "*", features = ["full"] }
warp = "0.3.7"
sled = "*"
lazy_static = "*"
thiserror = "*"
jsonwebtoken = { version = "*", features = ["aws_lc_rs"] }
# rocksdb = "*"
buckyos-kit = { workspace = true }
name-lib = { workspace = true }
kRPC = { workspace = true }
rbac = { workspace = true }


