[package]
name = "slog"
version = "0.1.0"
edition = "2024"

[dependencies]
flexi_logger = { workspace = true }
log = { workspace = true }
chrono = { workspace = true }
toml = { workspace = true }
serde_json = { workspace = true }
serde = { workspace = true }
rusqlite = { workspace = true }