[package]
name = "slog"
version = "0.1.0"
edition = "2024"

[dependencies]
flexi_logger = '*'
log = "*"
chrono = '*'
toml = "*"
serde_json = '1.0'
serde = { version = '*', features = ['derive'] }
rusqlite = { version = "*", features = ["bundled"] }