[package]
name = "repo_service"
version.workspace = true
edition = "2021"
authors = ["BuckyOS DAO","@waterflier"]

[dependencies]
time = { version = "^0.3", features = ["formatting"] }
async-trait = "*"
log = "*"
anyhow = "*"
serde = "*"
serde_json = "*"
url = "*"
tokio = { version = "*", features = ["full"] }
lazy_static = "*"
thiserror = "*"
semver = "*"
base64 = "*"
ed25519-dalek = { version = "*", features = ["pkcs8", "pem"] } 
async-recursion = "*"
jsonwebtoken = "*" 
futures-util = "*"
hex = "*"
rusqlite =  { version = "*", features = ["bundled"] }
sha2 = { version = ">=0.11.0-pre.4" }
reqwest = {version = "*", features = ["json", "rustls-tls"]}
bytes = "1"
http = "1"
http-body-util = "0.1"
ndn-lib = { workspace = true }
package-lib = { workspace = true }
name-lib = { workspace = true }
name-client = { workspace = true }
buckyos-kit = { workspace = true }
kRPC ={ workspace = true }
buckyos-api = { path = "../../kernel/buckyos-api" }
server-runner = { workspace = true }
cyfs-gateway-lib = { workspace = true }


