[package]
name = "repo_service"
version.workspace = true
edition = "2021"
authors = ["BuckyOS DAO","@waterflier"]

[dependencies]
time = { workspace = true }
async-trait = { workspace = true }
log = { workspace = true }
anyhow = { workspace = true }
serde = { workspace = true }
serde_json = { workspace = true }
url = { workspace = true }
tokio = { workspace = true }
lazy_static = { workspace = true }
thiserror = { workspace = true }
semver = { workspace = true }
base64 = { workspace = true }
ed25519-dalek = { workspace = true }
async-recursion = { workspace = true }
jsonwebtoken = { workspace = true }
futures-util = { workspace = true }
hex = { workspace = true }
rusqlite = { workspace = true }
sha2 = { workspace = true }
reqwest = { workspace = true, features = ["json", "rustls-tls"] }
bytes = { workspace = true }
http = { workspace = true }
http-body-util = { workspace = true }
ndn-lib = { workspace = true }
package-lib = { workspace = true }
name-lib = { workspace = true }
name-client = { workspace = true }
buckyos-kit = { workspace = true }
kRPC ={ workspace = true }
buckyos-api = { path = "../../kernel/buckyos-api" }
server-runner = { workspace = true }
cyfs-gateway-lib = { workspace = true }


