[package]
name = "control_panel"
version = "0.5.1"
edition = "2021"
authors = ["BuckyOS DAO","@sun"]

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
toml = { workspace = true }
clap = { workspace = true }
serde = { workspace = true }
serde_json = { workspace = true }
log ={ workspace = true }
simplelog = { workspace = true }
thiserror = { workspace = true }
tokio = { workspace = true }
async-trait = { workspace = true }
futures = { workspace = true }
lazy_static = { workspace = true }
jsonwebtoken ={ workspace = true }
num_cpus = { workspace = true }
reqwest = { workspace = true }
url = { workspace = true }
time = { workspace = true }
sysinfo ={ workspace = true }
chrono = { workspace = true }
if-addrs ={ workspace = true }
anyhow={ workspace = true }
server-runner = { workspace = true }
cyfs-gateway-lib = { workspace = true }
buckyos-kit = { workspace = true }
name-lib = { workspace = true }
name-client = { workspace = true }
package-lib = { workspace = true }
ndn-lib = { workspace = true }
kRPC = { workspace = true }
http = { workspace = true }
http-body-util = { workspace = true }
bytes = { workspace = true }
zip = { workspace = true }
base64 = { workspace = true }
uuid = { workspace = true }
rusqlite = { workspace = true }
buckyos-api = { path = "../../kernel/buckyos-api" }
