[package]
name = "kmsg"
version = "0.1.0"
edition = "2024"

[dependencies]
async-trait = { workspace = true }
serde = { workspace = true }
thiserror = { workspace = true }
tokio = { workspace = true }
sled = { workspace = true }
uuid = { workspace = true }
bincode = { workspace = true }
log = { workspace = true }
buckyos-kit = { workspace = true }
buckyos-api = {path="../buckyos-api"}
kRPC = { workspace = true }
anyhow = { workspace = true }
serde_json = { workspace = true }
server-runner = { workspace = true }
cyfs-gateway-lib = { workspace = true }
bytes = { workspace = true }
http = { workspace = true }
http-body-util = { workspace = true }
tempfile = { workspace = true }
