[package]
name = "scheduler"
version.workspace = true
edition = "2021"
authors = ["BuckyOS DAO","@waterflier"]


[dependencies]
time = { workspace = true }
async-trait = { workspace = true }
log = { workspace = true }
simplelog = { workspace = true }
serde = { workspace = true }
serde_json = { workspace = true }
url = { workspace = true }
tokio = { workspace = true }
lazy_static = { workspace = true }
thiserror = { workspace = true }
jsonwebtoken = { workspace = true }
toml = { workspace = true }
upon = { workspace = true }
anyhow = { workspace = true }
uuid = { workspace = true }
# rocksdb = "*"
buckyos-kit = { workspace = true }
name-lib = { workspace = true }
name-client = { workspace = true }
rbac = { workspace = true }
kRPC = { workspace = true }
buckyos-api = { path = "../buckyos-api" }
server-runner = { workspace = true }
cyfs-gateway-lib = { workspace = true }
bytes = { workspace = true }
http = { workspace = true }
http-body-util = { workspace = true }