[package]
name = "scheduler"
version.workspace = true
edition = "2021"
authors = ["BuckyOS DAO","@waterflier"]


[dependencies]
time = { version = "^0.3", features = ["formatting"] }
async-trait = "*"
log = "*"
simplelog = "*"
serde = "*"
serde_json = "*"
url = "*"
tokio = { version = "*", features = ["full"] }
warp = "0.3.7"
lazy_static = "*"
thiserror = "*"
jsonwebtoken = { version = "*", features = ["aws_lc_rs"] }
toml = "*"
upon = "*"
anyhow = "*"
uuid = { version = "*", features = ["v4"] }
# rocksdb = "*"
buckyos-kit = { workspace = true }
name-lib = { workspace = true }
name-client = { workspace = true }
rbac = { workspace = true }
kRPC = { workspace = true }
buckyos-api = { path = "../buckyos-api" }
server-runner = { workspace = true }
cyfs-gateway-lib = { workspace = true }
bytes = "1"
http = "1"
http-body-util = "0.1"