[package]
name = "verify_hub"
version.workspace = true
edition = "2021"
authors = ["BuckyOS DAO","@waterflier"]


[dependencies]
time = { workspace = true }
async-trait = { workspace = true }
log = { workspace = true }
simplelog = { workspace = true }
serde = { workspace = true }
serde_json = { workspace = true }
url = { workspace = true }
tokio = { workspace = true }
lazy_static = { workspace = true }
thiserror = { workspace = true }
jsonwebtoken = { workspace = true }
base64 = { workspace = true }
sha2 = { workspace = true }
rand = { workspace = true }
# rand_core = "*"
# rocksdb = "*"
buckyos-kit = { workspace = true }
name-lib = { workspace = true }
kRPC ={ workspace = true }
buckyos-api = { path = "../buckyos-api" }
server-runner = { workspace = true }
cyfs-gateway-lib = { workspace = true }
bytes = { workspace = true }
http = { workspace = true }
http-body-util = { workspace = true }