[package]
name = "verify_hub"
version.workspace = true
edition = "2021"
authors = ["BuckyOS DAO","@waterflier"]


[dependencies]
time = { version = "^0.3", features = ["formatting"] }
async-trait = "*"
log = "*"
simplelog = "*"
serde = "*"
serde_json = "*"
url = "*"
tokio = { version = "*", features = ["full"] }
warp = "0.3.7"
lazy_static = "*"
thiserror = "*"
jsonwebtoken = { version = "*", features = ["aws_lc_rs"] }
base64 = "*"
sha2 = "*"
rand = "*"
# rand_core = "*"
# rocksdb = "*"
buckyos-kit = { workspace = true }
name-lib = { workspace = true }
kRPC ={ workspace = true }
buckyos-api = { path = "../buckyos-api" }