[package]
name = "klog"
version = "0.1.0"
edition = "2024"

[dependencies]
openraft = { version = "0.9", features = ["serde", "storage-v2", "anyhow"]}
serde = { workspace = true }
tokio = { workspace = true }
async-trait = { workspace = true }
log = { workspace = true }
bincode = { workspace = true }
chrono = { workspace = true }
anyhow = { workspace = true }
anyerror = { workspace = true }
simplelog = { workspace = true }
tracing = { workspace = true }
tracing-subscriber = { workspace = true }
reqwest = { workspace = true }
thiserror = { workspace = true }
bytes = { workspace = true }