[package]
name = "slog_server"
version = "0.1.0"
edition = "2024"

[dependencies]
axum = "*"
slog = { path = "../../kernel/slog" }
log = "*"
tokio = { version = "*", features = ["full"] }
async-trait = "*"
serde_json = '1.0'
serde = { version = '*', features = ['derive'] }
rusqlite = { version = "*", features = ["bundled"] }