[package]
name = "slog_server"
version = "0.1.0"
edition = "2024"

[dependencies]
axum = { workspace = true }
slog = { path = "../../kernel/slog" }
log = { workspace = true }
tokio = { workspace = true }
async-trait = { workspace = true }
serde_json = { workspace = true }
serde = { workspace = true }
rusqlite = { workspace = true }