[workspace]
resolver = "2"

members = [

    "./cyfs_gateway/cyfs-gateway-lib",
    "./cyfs_gateway/cyfs_gateway",
    "./cyfs_gateway/cyfs-dns",
    "./cyfs_gateway/cyfs-warp",
    "./cyfs_gateway/cyfs-sn",
    "./cyfs_gateway/cyfs-socks",

    "./kernel/buckyos-api",
    "./kernel/sys_config_service",
    "./kernel/verify_hub",
    "./kernel/node_daemon",
    "./kernel/scheduler",
    "./kernel/task_manager",    

    "./frame/repo_service",
    "./frame/smb_service",

    "./tools/buckycli", 
    "test/test_rbac", "kernel/klog", "kernel/slog", "kernel/slog_daemon", "frame/slog_server", 
]

exclude = [
    "./tools/ns-tool",
    "./apps/tray-controller"
]
