[package]
name = "buckyos-api"
version.workspace = true
edition = "2021"
authors = ["BuckyOS DAO","@waterflier","@alexsunxl"]
# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
log = "*"
serde = "*"
serde_json = "*"
lazy_static = "*"
thiserror = "*"
rand = "*"
async-trait = "*"
chrono = "*"
once_cell = "*"
toml = "*"
tokio = { version = "*", features = ["full"] }
jsonwebtoken = { version = "*", features = ["aws_lc_rs"] }
reqwest = "*"
url = "*"

buckyos-kit = { workspace = true }
package-lib = { workspace = true }
name-lib = { workspace = true }
name-client = { workspace = true }
kRPC ={ workspace = true }
rbac = { workspace = true }

