[package]
name = "buckyos-api"
version.workspace = true
edition = "2021"
authors = ["BuckyOS DAO","@waterflier","@alexsunxl"]
# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
log = { workspace = true }
serde = { workspace = true }
serde_json = { workspace = true }
lazy_static = { workspace = true }
thiserror = { workspace = true }
rand = { workspace = true }
async-trait = { workspace = true }
chrono = { workspace = true }
once_cell = { workspace = true }
toml = { workspace = true }
tokio = { workspace = true }
jsonwebtoken = { workspace = true }
reqwest = { workspace = true }
url = { workspace = true }
base64 = { workspace = true }
ed25519-dalek = { workspace = true }
cyfs-sn = { workspace = true }

buckyos-kit = { workspace = true }
package-lib = { workspace = true }
name-lib = { workspace = true }
name-client = { workspace = true }
kRPC ={ workspace = true }
rbac = { workspace = true }

